//! Numerics suite — the checks that are about *values*, not about
//! whether an op compiles.
//!
//! Three kinds of test live here, and the distinction between them is the
//! point of the file:
//!
//! 1. **Tied weights under finite differences.** One [`Param`] feeding two
//!    paths must have its cotangents *accumulated*, not overwritten. The engine's
//!    engine claims this through its per-`Param` cached leaf; here it is
//!    verified independently, against finite differences and against the
//!    sum of the two single-path gradients.
//!
//! 2. **Analytic identities.** Facts that can be stated exactly and
//!    independently of any other library — `log_softmax` of a uniform row is
//!    `-ln n`, the sample variance of `1, 2, 3` is exactly `1`, the standard
//!    normal CDF at 1 is a tabulated constant. These are *not* reference
//!    vectors and must never be described as such; they are here because
//!    they are checkable without PyTorch, and because between them they pin
//!    the 16.9-WS4 semantics well enough to catch the mistakes that matter
//!    (an approximate GELU sold as the exact one, `correction = 0`).
//!
//! 3. **PyTorch reference vectors.** Generated by
//!    `tools/gen_reference_vectors.py` (torch **2.13.0**, pinned and asserted)
//!    into the committed `tests/data/reference_vectors.json`, and consumed
//!    below. These run by default and gate: a missing or malformed file is a
//!    hard failure carrying the regenerate command, never a skip.
//!
//!    rstorch is *not* bug-compatible with PyTorch, and two departures are
//!    deliberate. Both are asserted **from both sides** — torch's recorded
//!    answer and rstorch's — so neither can drift unnoticed:
//!
//!    * a fully `-inf` softmax row: torch NaN, rstorch `0` / `-inf`;
//!    * reductions over an empty axis: torch NaN (mean/var/std), an empty
//!      tensor (softmax) or a raise (max/min/argmax); rstorch returns the
//!      identity for `sum` and `Error::InvalidArg` for everything else.
//!
//!    Everywhere else the two must agree to [`REF_TOL`]. They do, with roughly
//!    two orders of magnitude of margin — the observed deviations are f32
//!    rounding, not formula error.
//!
//! This is an integration test rather than a unit-test module because every
//! assertion here is about the **public** contract (the semantics a user
//! reads in the docs), and because the reference loader reads a repo file at
//! runtime, which wants `CARGO_MANIFEST_DIR` and a real filesystem.

use rstorch::nn::{Mode, Param};
use rstorch::testing::check_grad;
use rstorch::{Device, Error, Result, Tensor};

const CPU: Device = Device::Cpu;

fn t(data: &[f32], shape: impl Into<rstorch::Shape>) -> Tensor {
    Tensor::from_vec(data.to_vec(), shape, &CPU).unwrap()
}

fn v(x: &Tensor) -> Vec<f32> {
    x.to_vec::<f32>().unwrap()
}

/// `Σ w ⊙ x` with pairwise-distinct constant weights: a scalar readout whose
/// cotangent is not a constant, so a gradient that lands in the wrong slot is
/// a wrong *number* and not merely a wrong arrangement.
fn wsum(x: &Tensor) -> Result<Tensor> {
    let w: Vec<f32> = (0..x.num_elements())
        .map(|i| 0.25 + 0.5 * (i as f32))
        .collect();
    x.mul(&Tensor::from_vec(w, x.dims().to_vec(), &CPU)?)?
        .sum_all()
}

// ===========================================================================
// 1. Tied weights
// ===========================================================================

/// The tied-weight objective: `w` is used **twice** — once to project `x` up
/// (`x @ wᵀ`) and once to project the result back down (`h @ w`), the shape
/// an input embedding tied to an output head has.
///
/// Written against plain tensors so `check_grad` can drive it; the `Param`
/// spelling below runs the identical arithmetic through `Param::get`.
fn tied(x: &Tensor, w: &Tensor) -> Result<Tensor> {
    let hidden = x.matmul(&w.transpose(-2, -1)?)?;
    wsum(&hidden.matmul(w)?)
}

/// Finite differences over an objective that uses one tensor on two paths.
///
/// This is the numeric half of the accumulation claim: the true derivative of
/// `f(w)` w.r.t. `w` is the sum of both paths' contributions, so a backward
/// that overwrote one with the other would disagree with the central
/// difference. Nothing here trusts the engine's bookkeeping.
#[test]
fn tied_weight_gradient_matches_finite_differences() {
    let x = t(&[0.5, -1.25, 2.0, 0.75, -0.5, 1.5], [2, 3]);
    let w = t(&[0.3, -0.7, 1.1, 0.9, 0.2, -1.3], [2, 3]);
    check_grad(|i| tied(&i[0], &i[1]), &[x, w], 1e-3, 1e-3).unwrap();
}

/// The same objective through a [`Param`], plus the decomposition that makes
/// "accumulated, not overwritten" a statement about numbers.
///
/// `detach` cuts one path at a time. The two single-path gradients are both
/// non-zero and **not equal to each other**, so:
///
/// * if the engine overwrote, the tied gradient would equal one of them;
/// * if it accumulated, it equals their sum — which is what is asserted.
#[test]
fn a_param_used_twice_accumulates_both_cotangents() {
    let x = t(&[0.5, -1.25, 2.0, 0.75, -0.5, 1.5], [2, 3]);
    let w = Param::new(t(&[0.3, -0.7, 1.1, 0.9, 0.2, -1.3], [2, 3]));

    // Both paths live: one `Param`, one cached leaf, two uses.
    let leaf = w.get(Mode::TRAIN);
    let tied_grad = v(&tied(&x, &leaf)
        .unwrap()
        .backward()
        .unwrap()
        .wrt(&w)
        .unwrap());

    // Path A only: the second use is detached, so only `x @ wᵀ` carries a
    // gradient.
    let leaf = w.get(Mode::TRAIN);
    let frozen = leaf.detach();
    let only_a = x
        .matmul(&leaf.transpose(-2, -1).unwrap())
        .unwrap()
        .matmul(&frozen)
        .unwrap();
    let grad_a = v(&wsum(&only_a).unwrap().backward().unwrap().wrt(&w).unwrap());

    // Path B only: the first use is detached.
    let leaf = w.get(Mode::TRAIN);
    let frozen = leaf.detach();
    let only_b = x
        .matmul(&frozen.transpose(-2, -1).unwrap())
        .unwrap()
        .matmul(&leaf)
        .unwrap();
    let grad_b = v(&wsum(&only_b).unwrap().backward().unwrap().wrt(&w).unwrap());

    // The premise of the test: the two paths really do contribute different,
    // non-trivial gradients. Without this the sum below proves nothing.
    assert!(grad_a.iter().any(|g| g.abs() > 1e-3), "{grad_a:?}");
    assert!(grad_b.iter().any(|g| g.abs() > 1e-3), "{grad_b:?}");
    assert!(
        grad_a
            .iter()
            .zip(&grad_b)
            .any(|(a, b)| (a - b).abs() > 1e-3),
        "the two paths must differ for the accumulation to be observable"
    );

    for (i, (&got, (&a, &b))) in tied_grad.iter().zip(grad_a.iter().zip(&grad_b)).enumerate() {
        let sum = a + b;
        assert!(
            (got - sum).abs() <= 1e-4 * sum.abs().max(1.0),
            "element {i}: tied gradient {got} is not path A {a} + path B {b} = {sum}"
        );
        // Spelt out: it is not either path alone.
        assert!(
            (got - a).abs() > 1e-6 || (a - b).abs() < 1e-6,
            "element {i}: tied gradient equals path A alone — overwritten, not accumulated"
        );
    }
}

/// Tying survives a `Param::set` (the optimizer step): the rebuilt leaf keeps
/// the parameter's identity, so the *next* graph still accumulates under the
/// same key.
#[test]
fn tying_still_accumulates_after_a_param_set() {
    let x = t(&[0.5, -1.25, 2.0, 0.75, -0.5, 1.5], [2, 3]);
    let mut w = Param::new(t(&[0.3, -0.7, 1.1, 0.9, 0.2, -1.3], [2, 3]));

    let before = v(&tied(&x, &w.get(Mode::TRAIN))
        .unwrap()
        .backward()
        .unwrap()
        .wrt(&w)
        .unwrap());

    w.set(t(&[0.3, -0.7, 1.1, 0.9, 0.2, -1.3], [2, 3])).unwrap();
    let after = v(&tied(&x, &w.get(Mode::TRAIN))
        .unwrap()
        .backward()
        .unwrap()
        .wrt(&w)
        .unwrap());

    assert_eq!(before.len(), after.len());
    for (i, (&a, &b)) in before.iter().zip(&after).enumerate() {
        assert!((a - b).abs() < 1e-5, "element {i}: {a} vs {b}");
    }
}

// ===========================================================================
// 2. Analytic identities — exact, and independent of any other library
// ===========================================================================

/// The standard normal CDF Φ at a few points, to 16 digits.
///
/// These are **tabulated mathematical constants**, not reference vectors:
/// Φ(z) = ½(1 + erf(z/√2)) is in every statistics table and is not a property
/// of any implementation. They are what lets this suite tell rstorch's
/// *exact* (erf) GELU from the tanh approximation without PyTorch: the two
/// disagree by ~1.5e-4 at z = 1 and ~5e-4 at z = 2, while an honest erf
/// agrees to f32 precision.
const PHI: [(f64, f64); 5] = [
    (-1.0, 0.158_655_253_931_457_05),
    (-0.5, 0.308_537_538_725_986_9),
    (0.5, 0.691_462_461_274_013_1),
    (1.0, 0.841_344_746_068_542_9),
    (2.0, 0.977_249_868_051_820_8),
];

#[test]
fn analytic_exact_gelu_is_x_times_the_normal_cdf() {
    for (z, phi) in PHI {
        let got = t(&[z as f32], ()).gelu().unwrap().item().unwrap();
        let want = z * phi;
        assert!(
            (got - want).abs() < 1e-6,
            "gelu({z}) = {got}, expected {want} (= {z} · Φ({z})); \
             a difference near 1e-4 means the tanh approximation, not the exact GELU"
        );
    }
}

#[test]
fn analytic_exact_gelu_at_zero_is_exactly_zero() {
    // Φ(0) = ½ exactly, so 0 · Φ(0) = 0 — no tolerance needed.
    assert_eq!(t(&[0.0], ()).gelu().unwrap().item().unwrap(), 0.0);
}

#[test]
fn analytic_gelu_satisfies_its_reflection_identity() {
    // gelu(x) − gelu(−x) = x·Φ(x) + x·(1 − Φ(x)) = x, for every x.
    // (True of the tanh approximation too, so this is a structural check on
    // the kernel, not evidence that the GELU is the exact one.)
    for x in [-3.0_f32, -0.75, 0.0, 0.4, 2.5] {
        let pos = t(&[x], ()).gelu().unwrap().item().unwrap();
        let neg = t(&[-x], ()).gelu().unwrap().item().unwrap();
        assert!(
            ((pos - neg) - f64::from(x)).abs() < 1e-5,
            "gelu({x}) − gelu({}) = {} ≠ {x}",
            -x,
            pos - neg
        );
    }
}

#[test]
fn analytic_gelu_derivative_at_zero_is_one_half() {
    // d/dx [x·Φ(x)] = Φ(x) + x·φ(x); at x = 0 that is Φ(0) = ½ exactly.
    let x = t(&[0.0], ()).traced().unwrap();
    let grads = x.gelu().unwrap().backward().unwrap();
    let g = grads.wrt_input(&x).unwrap().item().unwrap();
    assert!((g - 0.5).abs() < 1e-6, "gelu'(0) = {g}, expected 0.5");
}

#[test]
fn analytic_variance_uses_correction_one() {
    // Sample variance of 1, 2, 3: mean 2, squared deviations 1 + 0 + 1 = 2,
    // divided by n − 1 = 2, so exactly 1. With correction = 0 it would be ⅔ —
    // the two answers are far apart, which is the point of the case.
    let x = t(&[1.0, 2.0, 3.0], [3]);
    assert!((x.var_all().unwrap().item().unwrap() - 1.0).abs() < 1e-6);
    assert!((x.std_all().unwrap().item().unwrap() - 1.0).abs() < 1e-6);

    // Sample variance of 1, 2, 3, 4: deviations ±1.5, ±0.5 → 5 / 3.
    let x = t(&[1.0, 2.0, 3.0, 4.0], [4]);
    let want = 5.0 / 3.0;
    assert!((x.var_all().unwrap().item().unwrap() - want).abs() < 1e-6);

    // Axis-wise, on two rows with different spreads.
    let x = t(&[1.0, 2.0, 3.0, 2.0, 4.0, 6.0], [2, 3]);
    let got = v(&x.var(1).unwrap());
    assert!(
        (got[0] - 1.0).abs() < 1e-6 && (got[1] - 4.0).abs() < 1e-6,
        "{got:?}"
    );
}

#[test]
fn analytic_correction_one_rejects_a_single_sample() {
    // n − 1 = 0: there is no unbiased variance, and the policy is to say so
    // rather than return NaN.
    let x = t(&[3.5], [1]);
    assert!(matches!(x.var_all(), Err(Error::InvalidArg { .. })));
    assert!(matches!(x.std_all(), Err(Error::InvalidArg { .. })));
}

#[test]
fn analytic_softmax_of_a_uniform_row_is_one_over_n() {
    for n in [1usize, 3, 7] {
        let x = Tensor::zeros([1, n], rstorch::DType::F32, &CPU).unwrap();
        let p = v(&x.softmax(-1).unwrap());
        let l = v(&x.log_softmax(-1).unwrap());
        let want_p = 1.0 / n as f32;
        let want_l = -(n as f32).ln();
        for (i, (&pi, &li)) in p.iter().zip(&l).enumerate() {
            assert!((pi - want_p).abs() < 1e-6, "n={n} i={i}: {pi} vs {want_p}");
            assert!((li - want_l).abs() < 1e-5, "n={n} i={i}: {li} vs {want_l}");
        }
    }
}

#[test]
fn analytic_log_softmax_is_shift_invariant_and_sums_through_exp_to_one() {
    let x = t(&[0.3, -1.2, 2.0, 0.7], [1, 4]);
    let shifted = x.add_scalar(100.0).unwrap();
    let a = v(&x.log_softmax(-1).unwrap());
    let b = v(&shifted.log_softmax(-1).unwrap());
    for (i, (&ai, &bi)) in a.iter().zip(&b).enumerate() {
        assert!((ai - bi).abs() < 1e-5, "element {i}: {ai} vs {bi}");
    }
    let total: f32 = v(&x.softmax(-1).unwrap()).iter().sum();
    assert!((total - 1.0).abs() < 1e-6, "{total}");
}

#[test]
fn analytic_masked_softmax_ignores_the_masked_columns() {
    // Masking a column must give exactly the softmax of the surviving
    // columns — an identity, checkable without a reference.
    let logits = t(&[0.3, -1.2, 2.0, 0.7], [1, 4]);
    let mask = Tensor::from_vec(vec![false, true, false, true], [1, 4], &CPU).unwrap();
    let masked = logits
        .masked_fill(&mask, f64::NEG_INFINITY)
        .unwrap()
        .softmax(-1)
        .unwrap();
    let got = v(&masked);

    let survivors = t(&[0.3, 2.0], [1, 2]);
    let want = v(&survivors.softmax(-1).unwrap());

    assert_eq!(got[1], 0.0, "a masked column must be exactly zero: {got:?}");
    assert_eq!(got[3], 0.0, "a masked column must be exactly zero: {got:?}");
    assert!((got[0] - want[0]).abs() < 1e-6, "{got:?} vs {want:?}");
    assert!((got[2] - want[1]).abs() < 1e-6, "{got:?} vs {want:?}");
}

#[test]
fn analytic_a_fully_masked_row_is_zeros_not_nan() {
    // rstorch's documented divergence from PyTorch: exp(-inf − -inf) is NaN,
    // and NaN is not an answer. `p = 0` / `log p = -inf` is.
    let logits = t(&[0.3, -1.2, 2.0, 0.7, 1.1, -0.4], [2, 3]);
    let mask = Tensor::from_vec(vec![false, false, false, true, true, true], [2, 3], &CPU).unwrap();
    let masked = logits.masked_fill(&mask, f64::NEG_INFINITY).unwrap();

    let p = v(&masked.softmax(-1).unwrap());
    assert!(p.iter().all(|e| e.is_finite()), "{p:?}");
    assert_eq!(&p[3..], &[0.0, 0.0, 0.0], "fully-masked row must be zeros");
    assert!(((p[0] + p[1] + p[2]) - 1.0).abs() < 1e-6, "{p:?}");

    let l = v(&masked.log_softmax(-1).unwrap());
    assert!(
        l[3..].iter().all(|e| *e == f32::NEG_INFINITY),
        "fully-masked row of log_softmax must be -inf: {l:?}"
    );
    assert!(l[..3].iter().all(|e| e.is_finite()), "{l:?}");
}

#[test]
fn analytic_empty_reduction_policy() {
    // `sum` has an identity, so it returns it; nothing else does, so nothing
    // else guesses. (`src/tensor/ops/reduce.rs`.)
    let empty = Tensor::zeros([2, 0], rstorch::DType::F32, &CPU).unwrap();

    let summed = empty.sum(1).unwrap();
    assert_eq!(summed.dims(), &[2]);
    assert_eq!(v(&summed), vec![0.0, 0.0]);
    assert_eq!(empty.sum_all().unwrap().item().unwrap(), 0.0);

    macro_rules! refuses {
        ($($call:expr),+ $(,)?) => {
            $(assert!(
                matches!($call, Err(Error::InvalidArg { .. })),
                concat!(stringify!($call), " must refuse an empty axis"),
            );)+
        };
    }
    refuses!(
        empty.mean(1),
        empty.max(1),
        empty.min(1),
        empty.var(1),
        empty.std(1),
        empty.argmax(1),
        empty.argmin(1),
        empty.softmax(1),
        empty.log_softmax(1),
        empty.mean_all(),
        empty.max_all(),
        empty.min_all(),
    );
}

// ===========================================================================
// 3. PyTorch reference vectors
// ===========================================================================

/// Loading and comparing against `tests/data/reference_vectors.json`.
///
/// The file is **committed**, so a missing or malformed one is a hard failure
/// with the regenerate command in the message — never a skip. Every test in
/// this section runs by default and gates like any other.
mod vectors {
    use rstorch::{Device, Tensor};
    use serde_json::Value;

    /// Where `tools/gen_reference_vectors.py` writes, relative to the crate
    /// root.
    pub const PATH: &str = "tests/data/reference_vectors.json";

    const REGENERATE: &str =
        "regenerate with a pinned PyTorch:  python3 tools/gen_reference_vectors.py";

    /// The parsed reference file. Panics — loudly, and with the fix — if it
    /// is absent or unreadable.
    pub fn load() -> Value {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(PATH);
        let text = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("cannot read {} ({e}); {REGENERATE}", path.display()));
        serde_json::from_str(&text)
            .unwrap_or_else(|e| panic!("{} is not valid JSON ({e}); {REGENERATE}", path.display()))
    }

    /// One named case, with the version header checked first: a file produced
    /// by an unpinned torch is not the reference this suite was written
    /// against, and silently comparing to it would be the worst outcome.
    pub fn case<'a>(doc: &'a Value, name: &str) -> &'a Value {
        let pinned = string(doc, "pinned_torch");
        let actual = string(doc, "torch_version");
        assert!(
            actual.starts_with(pinned),
            "reference vectors were generated with torch {actual} but pin {pinned}; {REGENERATE}"
        );
        field(field(doc, "cases"), name)
    }

    /// A member, or a panic naming the missing key.
    pub fn field<'a>(value: &'a Value, key: &str) -> &'a Value {
        value
            .get(key)
            .unwrap_or_else(|| panic!("reference vectors: missing key `{key}`; {REGENERATE}"))
    }

    pub fn string<'a>(value: &'a Value, key: &str) -> &'a str {
        field(value, key)
            .as_str()
            .unwrap_or_else(|| panic!("reference vectors: `{key}` is not a string"))
    }

    /// One float, decoding the generator's non-finite spellings (strict JSON
    /// has no `NaN`/`Infinity` literals, so the generator writes strings).
    fn number(value: &Value) -> f64 {
        match value {
            Value::Number(n) => n
                .as_f64()
                .unwrap_or_else(|| panic!("reference vectors: `{n}` is not representable as f64")),
            Value::String(s) => match s.as_str() {
                "NaN" => f64::NAN,
                "Infinity" => f64::INFINITY,
                "-Infinity" => f64::NEG_INFINITY,
                other => panic!("reference vectors: `{other}` is not a float spelling"),
            },
            other => panic!("reference vectors: expected a float, got {other}"),
        }
    }

    pub fn floats(value: &Value, key: &str) -> Vec<f64> {
        array(value, key).iter().map(number).collect()
    }

    pub fn shape(value: &Value, key: &str) -> Vec<usize> {
        array(value, key)
            .iter()
            .map(|v| {
                v.as_u64()
                    .unwrap_or_else(|| panic!("reference vectors: `{key}` holds a non-dimension"))
                    as usize
            })
            .collect()
    }

    pub fn bools(value: &Value, key: &str) -> Vec<bool> {
        array(value, key)
            .iter()
            .map(|v| {
                v.as_bool()
                    .unwrap_or_else(|| panic!("reference vectors: `{key}` holds a non-boolean"))
            })
            .collect()
    }

    fn array<'a>(value: &'a Value, key: &str) -> &'a Vec<Value> {
        field(value, key)
            .as_array()
            .unwrap_or_else(|| panic!("reference vectors: `{key}` is not an array"))
    }

    /// A float32 tensor from a case's float array plus a shape.
    pub fn tensor(values: &[f64], dims: &[usize], device: &Device) -> Tensor {
        Tensor::from_vec(
            values.iter().map(|&v| v as f32).collect::<Vec<f32>>(),
            dims.to_vec(),
            device,
        )
        .unwrap()
    }

    /// Compare element-wise and return the **largest deviation observed**, so
    /// each test can report how much margin it actually has rather than only
    /// that it passed.
    ///
    /// `skip` names indices the comparison must not touch. It is only ever
    /// passed the indices of a *declared* divergence, and those indices are
    /// separately asserted on both sides by the caller — a skip here is never
    /// a place where nothing is checked.
    ///
    /// A NaN outside `skip` is a failure, not a match: rstorch produces NaN in
    /// exactly one documented place (an all-NaN max line) and none of these
    /// cases go near it.
    pub fn agree(got: &[f32], want: &[f64], tol: f64, skip: &[usize], what: &str) -> f64 {
        assert_eq!(got.len(), want.len(), "{what}: length");
        let mut worst = 0.0f64;
        for (i, (&g, &w)) in got.iter().zip(want).enumerate() {
            if skip.contains(&i) {
                continue;
            }
            let g = f64::from(g);
            assert!(
                !(w.is_nan() || g.is_nan()),
                "{what}[{i}]: NaN outside a declared divergence (rstorch {g} vs torch {w})"
            );
            if w.is_infinite() || g.is_infinite() {
                assert_eq!(g, w, "{what}[{i}]: infinities must match exactly");
                continue;
            }
            // Relative for large values, absolute for small: an f32 result
            // near zero carries no relative precision to compare.
            let deviation = (g - w).abs() / g.abs().max(w.abs()).max(1.0);
            assert!(
                deviation <= tol,
                "{what}[{i}]: rstorch {g} vs torch {w} (deviation {deviation:e}, tol {tol:e})"
            );
            worst = worst.max(deviation);
        }
        worst
    }
}

/// The comparison tolerance against the float64 references.
///
/// rstorch evaluates these in **f32** (~7 decimal digits) while the vectors
/// are f64, so the floor is the dtype, not the formula. Measured against
/// torch 2.13.0, the largest deviation in each family is:
///
/// | family | max deviation |
/// |---|---|
/// | exact GELU forward / backward | `4.1e-8` / `4.3e-8` |
/// | `var`/`std` `correction=1`, forward and backward | `7.8e-8` |
/// | masked softmax / log_softmax | `7.0e-8` / `8.9e-8` |
/// | masked softmax backward | `5.4e-7` |
///
/// all of them f32 rounding. `1e-5` keeps ~2 orders of magnitude of headroom
/// against platform differences in `erf` and summation order, while a wrong
/// *formula* — the tanh GELU, `correction = 0` — is off by `1e-4` or more and
/// still fails loudly. Each test prints its observed maximum, so a silent
/// drift toward the limit is visible with `--nocapture`.
const REF_TOL: f64 = 1e-5;

#[test]
fn reference_exact_gelu_forward_and_backward() {
    let doc = vectors::load();
    let case = vectors::case(&doc, "gelu_exact");
    let dims = vectors::shape(case, "shape");
    let input = vectors::floats(case, "input");
    let x = vectors::tensor(&input, &dims, &CPU);

    let forward = vectors::floats(case, "forward");
    let worst_f = vectors::agree(
        &v(&x.gelu().unwrap()),
        &forward,
        REF_TOL,
        &[],
        "gelu forward",
    );

    let traced = x.traced().unwrap();
    let grads = traced
        .gelu()
        .unwrap()
        .sum_all()
        .unwrap()
        .backward()
        .unwrap();
    let got = v(&grads.wrt_input(&traced).unwrap());
    let backward = vectors::floats(case, "backward");
    let worst_b = vectors::agree(&got, &backward, REF_TOL, &[], "gelu backward");

    eprintln!("gelu vs torch: max deviation {worst_f:e} forward, {worst_b:e} backward");
}

#[test]
fn reference_var_and_std_with_correction_one() {
    let doc = vectors::load();
    let mut worst = 0.0f64;
    for name in [
        "var_correction1_axis1",
        "var_correction1_all",
        "std_correction1_axis1",
        "std_correction1_all",
    ] {
        let case = vectors::case(&doc, name);
        let dims = vectors::shape(case, "shape");
        let input = vectors::floats(case, "input");
        let x = vectors::tensor(&input, &dims, &CPU);
        let over_axis = name.ends_with("axis1");
        let is_var = name.starts_with("var");

        // The generator passes `correction=1` explicitly; rstorch has no
        // other setting, which is the semantic being pinned.
        assert_eq!(vectors::field(case, "correction").as_u64(), Some(1));

        let reduce = |t: &Tensor| -> Result<Tensor> {
            match (is_var, over_axis) {
                (true, true) => t.var(1),
                (true, false) => t.var_all(),
                (false, true) => t.std(1),
                (false, false) => t.std_all(),
            }
        };

        let out = reduce(&x).unwrap();
        let forward = vectors::floats(case, "forward");
        worst = worst.max(vectors::agree(
            &v(&out),
            &forward,
            REF_TOL,
            &[],
            &format!("{name} forward"),
        ));

        // The generator differentiates a weighted readout; reproduce it
        // exactly, weights and all, so the gradients are comparable.
        let weights = vectors::floats(case, "readout_weights");
        let w = vectors::tensor(&weights, out.dims(), &CPU);
        let traced = x.traced().unwrap();
        let scalar = reduce(&traced).unwrap().mul(&w).unwrap().sum_all().unwrap();
        let got = v(&scalar.backward().unwrap().wrt_input(&traced).unwrap());
        let backward = vectors::floats(case, "backward");
        worst = worst.max(vectors::agree(
            &got,
            &backward,
            REF_TOL,
            &[],
            &format!("{name} backward"),
        ));
    }
    eprintln!("var/std correction=1 vs torch: max deviation {worst:e}");
}

#[test]
fn reference_masked_softmax_matches_torch_except_on_the_fully_masked_row() {
    let doc = vectors::load();
    let case = vectors::case(&doc, "softmax_masked");
    let dims = vectors::shape(case, "shape");
    let cols = dims[1];

    let logits = vectors::floats(case, "logits");
    let keep = vectors::bools(case, "keep_mask");
    let drop: Vec<bool> = keep.iter().map(|k| !k).collect();

    let x = vectors::tensor(&logits, &dims, &CPU);
    let mask = Tensor::from_vec(drop, dims.clone(), &CPU).unwrap();
    let masked = x.masked_fill(&mask, f64::NEG_INFINITY).unwrap();

    // The rows where rstorch deliberately disagrees with PyTorch. Everything
    // outside them is required to match; inside them both sides are pinned
    // explicitly below.
    let bad_rows = vectors::shape(case, "fully_masked_rows");
    assert!(
        !bad_rows.is_empty(),
        "the case must contain a fully-masked row"
    );
    let skip: Vec<usize> = bad_rows
        .iter()
        .flat_map(|&r| (r * cols)..((r + 1) * cols))
        .collect();

    let soft = vectors::floats(case, "softmax");
    let logsoft = vectors::floats(case, "log_softmax");
    let got_soft = v(&masked.softmax(-1).unwrap());
    let got_log = v(&masked.log_softmax(-1).unwrap());
    let worst_s = vectors::agree(&got_soft, &soft, REF_TOL, &skip, "masked softmax");
    let worst_l = vectors::agree(&got_log, &logsoft, REF_TOL, &skip, "masked log_softmax");

    // Divergence 1, asserted from both sides. torch's recorded answer must
    // still be the NaN this policy exists to avoid, and rstorch's must be the
    // documented zero / -inf. Either side changing fails the test.
    for &i in &skip {
        assert!(
            soft[i].is_nan(),
            "torch's fully-masked softmax is no longer NaN at {i} ({}); the divergence \
             note in tools/gen_reference_vectors.py needs revisiting",
            soft[i]
        );
        assert!(
            logsoft[i].is_nan(),
            "torch's fully-masked log_softmax is no longer NaN at {i} ({})",
            logsoft[i]
        );
        assert_eq!(got_soft[i], 0.0, "rstorch fully-masked softmax at {i}");
        assert_eq!(
            got_log[i],
            f32::NEG_INFINITY,
            "rstorch fully-masked log_softmax at {i}"
        );
    }

    // A *partially* masked row is not a divergence: both libraries put an
    // exact zero in the masked column, and `agree` already compared them.
    // Spelt out here so the distinction between the two cases is explicit.
    for (i, &k) in keep.iter().enumerate() {
        if !k && !skip.contains(&i) {
            assert_eq!(got_soft[i], 0.0, "masked column {i}");
            assert_eq!(soft[i], 0.0, "torch masked column {i}");
            assert_eq!(got_log[i], f32::NEG_INFINITY, "masked column {i}");
        }
    }

    // And the backward, on the rows where both libraries agree there is an
    // answer at all.
    let weights = vectors::floats(case, "readout_weights");
    let w = vectors::tensor(&weights, &dims, &CPU);
    let traced = masked.traced().unwrap();
    let scalar = traced
        .softmax(-1)
        .unwrap()
        .mul(&w)
        .unwrap()
        .sum_all()
        .unwrap();
    let got = v(&scalar.backward().unwrap().wrt_input(&traced).unwrap());
    let want = vectors::floats(case, "softmax_backward");
    let worst_b = vectors::agree(&got, &want, REF_TOL, &skip, "masked softmax backward");

    eprintln!(
        "masked softmax vs torch: max deviation {worst_s:e} softmax, {worst_l:e} log_softmax, \
         {worst_b:e} backward (fully-masked row {bad_rows:?} is a declared divergence)"
    );
}

/// What torch does with a reduction over an empty axis, as this suite expects
/// to find it recorded. Hard-coded rather than read from the file, so that a
/// *regenerated* file whose torch behaviour has changed fails here instead of
/// quietly redefining the reference.
#[derive(Debug, PartialEq)]
enum TorchOnEmpty {
    /// Returned values, all non-finite (`NaN`).
    NotANumber,
    /// Raised.
    Raised,
    /// Returned an empty tensor — the reduction kept the empty axis.
    EmptyTensor,
    /// Returned the identity element.
    Identity,
}

#[test]
fn reference_empty_reduction_pins_both_policies() {
    // This case does not assert parity: rstorch's empty-reduction policy is a
    // *deliberate* departure — `sum` returns the identity
    // and everything else refuses, rather than returning NaN or an empty
    // tensor. What it asserts is both sides at once, so neither can drift
    // unnoticed.
    use TorchOnEmpty::{EmptyTensor, Identity, NotANumber, Raised};

    let doc = vectors::load();
    let case = vectors::case(&doc, "empty_reduction_policy");
    let torch = vectors::field(case, "torch");
    let empty = Tensor::zeros([2, 0], rstorch::DType::F32, &CPU).unwrap();

    // `sum` is the one place the two libraries agree.
    let sum = vectors::field(torch, "sum");
    assert_eq!(vectors::string(sum, "status"), "ok");
    let want = vectors::floats(sum, "values");
    let worst = vectors::agree(&v(&empty.sum(1).unwrap()), &want, REF_TOL, &[], "empty sum");
    assert_eq!(empty.sum_all().unwrap().item().unwrap(), 0.0);

    let expected = [
        ("sum", Identity),
        ("mean", NotANumber),
        ("max", Raised),
        ("min", Raised),
        ("var", NotANumber),
        ("std", NotANumber),
        ("argmax", Raised),
        ("softmax", EmptyTensor),
    ];

    for (name, want) in expected {
        let entry = vectors::field(torch, name);
        let got = match vectors::string(entry, "status") {
            "error" => Raised,
            _ => {
                let values = vectors::floats(entry, "values");
                if values.is_empty() {
                    EmptyTensor
                } else if values.iter().all(|v| v.is_nan()) {
                    NotANumber
                } else {
                    Identity
                }
            }
        };
        assert_eq!(
            got, want,
            "torch {name} over an empty axis is now {got:?}, was {want:?} when rstorch's \
             empty-reduction policy was written — re-examine the policy, do not just \
             update this table"
        );

        // rstorch's side: everything but `sum` refuses, whatever torch did.
        if name == "sum" {
            continue;
        }
        let refused = match name {
            "mean" => empty.mean(1).err(),
            "max" => empty.max(1).err(),
            "min" => empty.min(1).err(),
            "var" => empty.var(1).err(),
            "std" => empty.std(1).err(),
            "argmax" => empty.argmax(1).err(),
            _ => empty.softmax(1).err(),
        };
        assert!(
            matches!(refused, Some(Error::InvalidArg { .. })),
            "{name}: rstorch must refuse an empty axis, got {refused:?}"
        );
    }

    eprintln!(
        "empty reductions: `sum` agrees with torch (max deviation {worst:e}); \
         mean/var/std diverge (torch NaN, rstorch InvalidArg); softmax diverges \
         (torch empty tensor, rstorch InvalidArg); max/min/argmax both refuse"
    );
}
