//! Wide-accumulator arithmetic shared by every numeric CPU kernel.
//!
//! Kernels accumulate in [`Element::Acc`](crate::dtype::Element::Acc) rather
//! than in the element dtype, which is what stops a long `f16` sum from
//! saturating to infinity. [`NumAcc`] is that arithmetic; [`FloatAcc`] adds the
//! float-only extras the fused kernels need. Both are generated by
//! [`impl_acc!`] so the implementing types cannot drift apart.
//!
//! The set of implementing types *is* the dtype gate, in both directions:
//!
//! - `bool` has `Acc = bool` and implements neither, so a bool reduce, matmul,
//!   index-add, or conv is rejected loudly before a generic kernel is ever
//!   instantiated.
//! - `i64` implements [`NumAcc`] but deliberately **not** [`FloatAcc`], which
//!   is what makes softmax, `LayerNorm`, and the optimizer steps decline an
//!   integer dtype rather than do something numerically meaningless.
//!
//! Three *different* extremum rules live here and are not interchangeable:
//! [`max`](NumAcc::max)/[`min`](NumAcc::min) (running extremum, NaN
//! propagating, receiver wins a tie), [`order`](NumAcc::order) (a total order
//! for `argmax`/`argmin`, with NaN excluded by the caller), and
//! [`beats`](NumAcc::beats) (strictly-better test for pooling, where the first
//! NaN wins). `elementwise.rs`'s `maximum`/`minimum` are a *fourth* rule —
//! IEEE `max`/`min` once NaN is excluded, which answers `+0.0` where
//! [`max`](NumAcc::max) answers `-0.0` — and stay there.

use std::cmp::Ordering;
use std::ops::{Add, Div, Mul, Sub};

/// Wide-accumulator arithmetic for the reduction, matmul, conv/pool, and
/// index-accumulation kernels. See the [module docs](self) for which types
/// implement it and why `bool` does not.
pub(crate) trait NumAcc: Copy {
    /// The additive identity — the `Sum`/`Mean`, inner-product, and
    /// window-accumulation seed.
    const ZERO: Self;
    /// Widening sum step. Integers wrap rather than panicking in debug and
    /// silently differing in release.
    fn add(self, other: Self) -> Self;
    /// Widening product; integers wrap for the same reason.
    fn mul(self, other: Self) -> Self;
    /// Multiply-add step `self + a*b`, kept as separate ops so integer
    /// accumulation wraps deterministically rather than aborting on a debug
    /// overflow — matmul over huge i64 magnitudes is a defined wrap.
    fn mul_add(self, a: Self, b: Self) -> Self;
    /// Divide an accumulated sum by a (wide) element count — `Mean`'s axis
    /// length, or `AvgPool2d`'s window area — widening the count inside the
    /// impl. Integer division truncates toward zero: `PyTorch` offers no integer
    /// mean, and an integer average has no single obvious rounding rule.
    fn div_count(self, count: usize) -> Self;
    /// Running maximum, propagating NaN (so a NaN anywhere in the axis wins,
    /// matching `PyTorch`) and keeping the receiver on a tie.
    fn max(self, other: Self) -> Self;
    /// Running minimum, propagating NaN.
    fn min(self, other: Self) -> Self;
    /// Order two accumulated values for `argmax`/`argmin`, with the first
    /// occurrence winning a tie (as in `PyTorch`).
    ///
    /// NaN never reaches here: `arg_reduce_generic` settles a NaN candidate
    /// before comparing, because a NaN must win *both* directions and so
    /// cannot be expressed as a position in any single total order.
    fn order(self, other: Self) -> Ordering;
    /// Whether `self` strictly beats `other` as a running maximum.
    ///
    /// NaN beats every number but not another NaN, so a window containing a
    /// NaN pools to NaN (`PyTorch`'s propagation) and the **first** NaN — or,
    /// with no NaN, the first occurrence of the maximum — owns the gradient.
    ///
    /// Deliberately *not* [`max`](NumAcc::max) or [`order`](NumAcc::order):
    /// the tie-breaking and NaN rules differ from both.
    fn beats(self, other: Self) -> bool;
    /// Whether this value is NaN — always `false` for integer accumulators.
    ///
    /// Arg-reductions need this because a NaN anywhere in the line is the
    /// selected element for both `argmax` and `argmin`, which is what keeps
    /// them consistent with `max`/`min` (both of which propagate NaN).
    fn is_nan(self) -> bool;
}

/// The float-only accumulator extras used by the fused kernels.
///
/// Implemented for `f32` and `f64` only; the missing `i64` impl is what
/// rejects integer dtypes from softmax, `LayerNorm`, and the optimizer steps.
pub(crate) trait FloatAcc:
    NumAcc
    + PartialEq
    + PartialOrd
    + Add<Output = Self>
    + Sub<Output = Self>
    + Mul<Output = Self>
    + Div<Output = Self>
{
    /// Negative infinity — softmax's row-peak seed.
    const NEG_INFINITY: Self;
    /// Widen a count (a row width, or a literal `1`) into the accumulator.
    fn from_usize(value: usize) -> Self;
    /// `e^self`.
    fn exp(self) -> Self;
    /// Square root.
    fn sqrt(self) -> Self;
}

/// Generate the accumulator impls for one type.
///
/// `float` additionally emits the [`FloatAcc`] impl; `int` deliberately does
/// not, which is the whole float-only gate.
macro_rules! impl_acc {
    (float $ty:ty) => {
        impl NumAcc for $ty {
            const ZERO: Self = 0.0;

            #[inline]
            fn add(self, other: Self) -> Self {
                self + other
            }
            #[inline]
            fn mul(self, other: Self) -> Self {
                self * other
            }
            #[inline]
            fn mul_add(self, a: Self, b: Self) -> Self {
                self + a * b
            }
            #[inline]
            fn div_count(self, count: usize) -> Self {
                self / (count as $ty)
            }
            #[inline]
            fn max(self, other: Self) -> Self {
                if self.is_nan() || other.is_nan() {
                    <$ty>::NAN
                } else if self >= other {
                    self
                } else {
                    other
                }
            }
            #[inline]
            fn min(self, other: Self) -> Self {
                if self.is_nan() || other.is_nan() {
                    <$ty>::NAN
                } else if self <= other {
                    self
                } else {
                    other
                }
            }
            #[inline]
            fn order(self, other: Self) -> Ordering {
                self.partial_cmp(&other).unwrap_or(Ordering::Equal)
            }
            #[inline]
            fn beats(self, other: Self) -> bool {
                if self.is_nan() {
                    !other.is_nan()
                } else {
                    !other.is_nan() && self > other
                }
            }
            #[inline]
            fn is_nan(self) -> bool {
                <$ty>::is_nan(self)
            }
        }

        impl FloatAcc for $ty {
            const NEG_INFINITY: Self = Self::NEG_INFINITY;

            #[inline]
            fn from_usize(value: usize) -> Self {
                value as Self
            }
            #[inline]
            fn exp(self) -> Self {
                self.exp()
            }
            #[inline]
            fn sqrt(self) -> Self {
                self.sqrt()
            }
        }
    };
    (int $ty:ty) => {
        impl NumAcc for $ty {
            const ZERO: Self = 0;

            #[inline]
            fn add(self, other: Self) -> Self {
                self.wrapping_add(other)
            }
            #[inline]
            fn mul(self, other: Self) -> Self {
                self.wrapping_mul(other)
            }
            #[inline]
            fn mul_add(self, a: Self, b: Self) -> Self {
                self.wrapping_add(a.wrapping_mul(b))
            }
            #[inline]
            fn div_count(self, count: usize) -> Self {
                self / (count as $ty)
            }
            #[inline]
            fn max(self, other: Self) -> Self {
                Ord::max(self, other)
            }
            #[inline]
            fn min(self, other: Self) -> Self {
                Ord::min(self, other)
            }
            #[inline]
            fn order(self, other: Self) -> Ordering {
                Ord::cmp(&self, &other)
            }
            #[inline]
            fn beats(self, other: Self) -> bool {
                self > other
            }
            #[inline]
            fn is_nan(self) -> bool {
                false
            }
        }
    };
}

impl_acc!(float f32);
impl_acc!(float f64);
impl_acc!(int i64);
